### ISSUE TITLE
Hal9k IR og Arduino UNO

### ISSUE THREAD

**Issue by tsvane** [MTrab/Kamstrup#1]
Hej Morten.

Jeg har brugt det meste af weekenden på at få dit projekt til at køre på min Arduino UNO (rev 3e) og Hal9k IR modul ([https://wiki.hal9k.dk/projects/kamstrup](https://wiki.hal9k.dk/projects/kamstrup)) sammen med min Kamstrup Omnipower el-måler. Men uden held. Skulle der være nogen åbenlyse komplikationer i dette setup? Jeg er rimlig ny til det her med Arduino, så det kan være jeg er helt på vildspor.

Jeg har forsøgt mig med at tilføje en serial.print med rxindex for at se om der overhovedet bliver modtaget noget data, men denne er altid 0 når IR-modulet sidder på måleren.
Men hvis jeg tager en fjernbetjening og peger mod RX-dioden viser den fint at der modtages data. Ligeledes kan jeg konstatere at TX-dioden lyser når jeg ser på den med et kamera.

Kan det være at måleren har fået slået IR-interfacet fra?

Med venlig hilsen
Tobias

**Comment by MTrab** [comment]
Jeg har selv forsøgt med Hal9k's modul og har aldrig fået det til at virke.
Bl.a. derfor jeg har lavet dette forsimplet setup, som virker.

Men igen - denne kode er ikke kompatibel med Hal9k's modul, det er helt udelukket.

**Comment by tsvane** [comment]
OK, tak for hurtigt svar :)

**Comment by anderssvante** [comment]
Hej Morten
Jeg har også forsøgt mig med både [HAL9k og din løsning uden held](https://forum.arduino.cc/index.php?topic=596890.0). 
Det tætteste jeg kom på noget, der lignede en respons, var: 
>  -- Aflæser Kamstrup Elmåler --
> 
> Energy in: 0.00 Wh
> Current Power: 0.00 k|qv{??????????????????S??????????????????
> !*4BMXcny????
> Voltage p1: 0.00 kVA
> Voltage p2: 0.00 MVA
> Voltage p3: 0.00 GVA
> Energy out: 0.00 kWh
> Current p1: 0.00 bar
> Current p2: 0.00 RTC
> Current p3: 0.00 ASCII
> Power p1: 0.00 ton x 10
> Power p2: 0.00 GJ x 10
> Power p3: 0.00 minutes

Jeg kan ikke lige lure hvad opkastet efter "Current power" er? Samt hvorfor alle værdier er nul.
Du skriver at du havde besværligheder med boarddefinitionerne - hvad gik dét på?

mvh Anders

**Comment by MTrab** [comment]
Det ligner du er udsat for det samme som jeg er blevet.
Aura har deaktiveret IR interfacet her i området hvor jeg bor.

Min begyndte at skrive som din, og jeg har derfor snakket med Aura, som har deaktiveret IR interface som følge af GDPR - det bliver ikke aktiveret igen, desværre.

**Comment by anderssvante** [comment]
Takker. Så giver det ikke meget mening, at kaste flere arbejdstimer efter at prøve at få det til at virke.
